title: Iman Tabrizian Personal Homepage
url: 'http://imantabrizian.me'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Iman Tabrizian
tagline: Student
pic: profile.jpg #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: tabrizian@outlook.com
website: blog.imantabrizian.me #do not add http://
linkedin: tabrizian
github: tabrizian
twitter: '@ImanTabrizian'
stackoverflow: users/4453461/iman
stackoverflow-display: iman

#Update all the sections by editing the files inside _includes folder.
